#%RAML 1.0 Library
usage: Exercises type

types:
  Exe02RequestType: 
    type: !include ../types/exe02request.raml  
  Exe02ResponseType: 
    type: !include ../types/exe02response.raml
  
  Exe03RequestType: 
    type: !include ../types/exe03request.raml  
  Exe03ResponseType: 
    type: !include ../types/exe03response.raml

  Exe04RequestType: 
    type: !include ../types/exe04request.raml  
  Exe04ResponseType: 
    type: !include ../types/exe04response.raml
  
  Exe05RequestType: 
    type: !include ../types/exe05request.raml  
  Exe05ResponseType: 
    type: !include ../types/exe05response.raml

  Exe06RequestType: 
    type: !include ../types/exe06request.raml  
  Exe06ResponseType: 
    type: !include ../types/exe06response.raml

  Exe07RequestType: 
    type: !include ../types/exe07request.raml  
  Exe07ResponseType: 
    type: !include ../types/exe07response.raml

  Exe08RequestType: 
    type: !include ../types/exe08request.raml  
  Exe08ResponseType: 
    type: !include ../types/exe08response.raml

  Exe09RequestType: 
    type: !include ../types/exe09request.raml  
  Exe09ResponseType: 
    type: !include ../types/exe09response.raml
  
  Exe10RequestType: 
    type: !include ../types/exe10request.raml  
  Exe10ResponseType: 
    type: !include ../types/exe10response.raml

  Exe11RequestType: 
    type: !include ../types/exe11request.raml  
  Exe11ResponseType: 
    type: !include ../types/exe11response.raml
  
  Exe12RequestType: 
    type: !include ../types/exe12request.raml  
  Exe12ResponseType: 
    type: !include ../types/exe12response.raml

  Exe13RequestType: 
    type: !include ../types/exe13request.raml  
  Exe13ResponseType: 
    type: !include ../types/exe13response.raml

  Exe14RequestType: 
    type: !include ../types/exe14request.raml  
  Exe14ResponseType: 
    type: !include ../types/exe14response.raml

  Exe15RequestType: 
    type: !include ../types/exe15request.raml  
  Exe15ResponseType: 
    type: !include ../types/exe15response.raml

  Exe16RequestType: 
    type: !include ../types/exe16request.raml  
  Exe16ResponseType: 
    type: !include ../types/exe16response.raml

  Exe17RequestType: 
    type: !include ../types/exe17request.raml  
  Exe17ResponseType: 
    type: !include ../types/exe17response.raml

  Exe18RequestType: 
    type: !include ../types/exe18request.raml  
  Exe18ResponseType: 
    type: !include ../types/exe18response.raml