#%RAML 1.0 DataType

type: object
properties:
  response:
    type: object
    properties:
      area:
        type: string
        example: 'A área do quadrado é: 100 m2'
      dobro_area:
        type: string
        example: 'O dobro desta área é: 200 m2'