#%RAML 1.0 DataType

type: object
properties:
  response:
    type: object
    properties:
      excesso:
        type: string
        example: 'Peso excedente é: 25.45 Kg'
      multa:
        type: string
        example: 'Multa é: R$ 101.80'
