#%RAML 1.0 DataType

type: object
properties:
  response:
    type: object
    properties:
      salario_bruto:
        type: number
        example: 4410
      ir:
        type: number
        example: 485.1
      inss:
        type: number
        example: 352.8
      sindicato:
        type: number
        example: 220.5
      salario_liquido:
        type: number
        example: 3351.6
