#%RAML 1.0 DataType

type: object
properties:
  nota_01:
    type: integer
    example: 9
  nota_02:
    type: integer
    example: 8
  nota_03:
    type: integer
    example: 7
  nota_04:
    type: integer
    example: 6