#%RAML 1.0 DataType

type: object
properties:
  response:
    type: object
    properties:
      a:
        type: integer
        example: 3
      b:
        type: number
        example: 5.4
      c:
        type: number
        example: 13.824
